/**
 * Generated by catalog/build-pages.mjs — do not edit by hand.
 * Advanced-mode Pages Worker: serves /v1/plugins (provider page) and
 * /catalog-source.json (manifest) with an explicit JSON content type. The
 * manifest endpoint is derived from the request origin so the source stays
 * self-consistent no matter which hostname it is deployed to.
 */
const PAGE = "{\n  \"schemaVersion\": \"1.0.0\",\n  \"generatedAt\": \"2026-09-18T09:38:58Z\",\n  \"revision\": \"2026-09-18T09:38:58Z\",\n  \"items\": [\n    {\n      \"id\": \"fal-imagegen\",\n      \"name\": \"dsh-fal-imagegen\",\n      \"displayName\": \"fal 生图（fal.ai 原生）\",\n      \"summary\": \"fal.ai 原生生图：设置卡片跟随 DSH 语言（中文/英文，默认英文）+ Agent 工具 fal_generate_image（异步提交）/ fal_get_image_task（后台任务查询）/ fal_edit_image / fal_list_image_models，直连 queue.fal.run（Key 鉴权、队列轮询），默认模型 openai/gpt-image-2.5/flare。\",\n      \"homepage\": \"https://github.com/Enchanted0911/dsh-fal-imagegen\",\n      \"latestVersion\": \"0.2.0\",\n      \"license\": \"MIT\",\n      \"categories\": [\n        \"image-generation\",\n        \"agent-tools\",\n        \"interface\"\n      ],\n      \"keywords\": [\n        \"fal\",\n        \"fal.ai\",\n        \"text-to-image\",\n        \"image-to-image\",\n        \"gpt-image-2.5\",\n        \"nano-banana\",\n        \"flux\"\n      ],\n      \"repository\": {\n        \"url\": \"https://github.com/Enchanted0911/dsh-fal-imagegen\"\n      },\n      \"package\": {\n        \"registry\": \"npm\",\n        \"name\": \"dsh-fal-imagegen\"\n      },\n      \"publisher\": {\n        \"name\": \"wujunsheng\",\n        \"url\": \"https://github.com/Enchanted0911\"\n      },\n      \"capabilities\": {\n        \"required\": [\n          \"tools\",\n          \"settings\"\n        ],\n        \"optional\": [\n          \"attachments\",\n          \"systemPrompt\"\n        ]\n      },\n      \"compatibility\": {\n        \"apiVersion\": \"1.x\",\n        \"hosts\": [\n          \"dsh>=0.1.5-rc.2\"\n        ]\n      },\n      \"updatedAt\": \"2026-09-18T09:38:58Z\"\n    }\n  ],\n  \"page\": {\n    \"total\": 1\n  }\n}\n"
const MANIFEST_TEMPLATE = "{\n  \"manifestVersion\": \"1.0.0\",\n  \"providerId\": \"dev.wujunsheng.dsh-fal-imagegen-catalog\",\n  \"name\": \"dsh-fal-imagegen 目录源\",\n  \"description\": \"个人维护的 DSH 插件目录源，目前收录 dsh-fal-imagegen（fal.ai 原生插件）。\",\n  \"homepage\": \"https://github.com/Enchanted0911/dsh-fal-imagegen\",\n  \"attribution\": {\n    \"name\": \"wujunsheng\",\n    \"url\": \"https://github.com/Enchanted0911\"\n  },\n  \"transport\": {\n    \"kind\": \"https-json\",\n    \"endpoint\": \"__SELF_ORIGIN__/v1/plugins\",\n    \"method\": \"GET\"\n  },\n  \"query\": {\n    \"supported\": [\n      \"q\",\n      \"category\",\n      \"cursor\",\n      \"limit\"\n    ],\n    \"defaultLimit\": 50,\n    \"maxLimit\": 50,\n    \"sorts\": []\n  },\n  \"updatedAt\": \"2026-09-18T09:38:58Z\"\n}\n"

const JSON_HEADERS = {
  'content-type': 'application/json; charset=utf-8',
  'cache-control': 'public, max-age=300',
  'access-control-allow-origin': '*',
}

export default {
  async fetch(request, env) {
    const url = new URL(request.url)
    if (url.pathname === '/v1/plugins') {
      return new Response(PAGE, { headers: JSON_HEADERS })
    }
    if (url.pathname === '/catalog-source.json') {
      const manifest = MANIFEST_TEMPLATE.replace('__SELF_ORIGIN__', url.origin)
      return new Response(manifest, { headers: JSON_HEADERS })
    }
    // Everything else: try the static assets (catalog-source.json among them).
    if (env.ASSETS !== undefined) {
      const asset = await env.ASSETS.fetch(request)
      if (asset.status === 404) return json({ error: 'not found' }, 404)
      return asset
    }
    return json({ error: 'not found' }, 404)
  },
}

function json(value, status = 200) {
  return new Response(JSON.stringify(value), { status, headers: JSON_HEADERS })
}
