/**
 * Emit the Cloudflare Pages variant of the catalog source.
 *
 *   node catalog/build-pages.mjs https://dsh-fal-imagegen-catalog.pages.dev
 *
 * Writes:
 *   catalog/pages/catalog-source.json        static manifest (origin = arg)
 *   catalog/pages/functions/v1/plugins.js    a Pages Function serving the
 *                                            provider page with an explicit
 *                                            `application/json` content type
 *
 * The Function form is what makes Pages viable: a static host names the
 * content type from the file extension, so the extensionless `/v1/plugins`
 * would come back as `application/octet-stream`, and the market's network
 * boundary (restricted-http.ts) rejects anything that is not
 * `application/json`/`+json`. The function sets the header itself.
 *
 * Deploy (in the repo root, after `npx wrangler login`):
 *   npx wrangler pages deploy catalog/pages --project-name dsh-fal-imagegen-catalog
 * → https://dsh-fal-imagegen-catalog.pages.dev
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { buildManifest, buildPage, PLUGIN } from './entry.mjs'

const here = dirname(fileURLToPath(import.meta.url))
const root = join(here, '..')
const out = join(here, 'pages')
const origin = process.argv[2] ?? 'https://REPLACE-WITH-YOUR-PAGES-URL'

// Keep the catalog's version honest against the package it describes.
const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'))
if (pkg.version !== PLUGIN.latestVersion) {
  console.warn(`warning: catalog entry says ${PLUGIN.latestVersion} but package.json says ${pkg.version}`)
}

const pageJson = `${JSON.stringify(buildPage(), null, 2)}\n`

mkdSynced(join(out, 'functions', 'v1'))
writeFileSync(join(out, 'catalog-source.json'), `${JSON.stringify(buildManifest(origin), null, 2)}\n`)
writeFileSync(join(out, 'functions', 'v1', 'plugins.js'), `/**
 * Generated by catalog/build-pages.mjs — do not edit by hand.
 * Serves the v1 provider page at /v1/plugins with an explicit JSON content type.
 */
const PAGE = ${JSON.stringify(pageJson)}

export function onRequestGet() {
  return new Response(PAGE, {
    headers: {
      'content-type': 'application/json; charset=utf-8',
      'cache-control': 'public, max-age=300',
      'access-control-allow-origin': '*',
    },
  })
}
`)
console.log(`wrote pages/catalog-source.json (origin ${origin}) and pages/functions/v1/plugins.js`)

function mkdSynced(dir) {
  mkdirSync(dir, { recursive: true })
}