/**
 * Emit the Cloudflare Pages variant of the catalog source.
 *
 *   node catalog/build-pages.mjs https://dsh-fal-imagegen-catalog.pages.dev
 *
 * Writes:
 *   catalog/pages/catalog-source.json   static manifest (origin = arg)
 *   catalog/pages/_worker.js            an advanced-mode Pages Worker serving
 *                                       /v1/plugins with an explicit
 *                                       `application/json` content type and a
 *                                       self-consistent manifest at
 *                                       /catalog-source.json
 *
 * Why `_worker.js` and not a `functions/` directory: the v1 contract needs
 * the extensionless `/v1/plugins` to answer `application/json`, and a static
 * host names the content type from the file extension — so the path would
 * come back as a non-JSON type and the market's network boundary
 * (restricted-http.ts) would reject it. Wrangler v4 has deprecated the
 * Pages Functions pipeline, so a self-contained advanced-mode `_worker.js`
 * is the form that keeps working on current wrangler versions. Deploying is
 * still the same command:
 *
 *   npx wrangler pages deploy catalog/pages --project-name dsh-fal-imagegen-catalog
 * → https://dsh-fal-imagegen-catalog.pages.dev
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { buildManifest, buildPage, PLUGIN } from './entry.mjs'

const here = dirname(fileURLToPath(import.meta.url))
const root = join(here, '..')
const out = join(here, 'pages')
const origin = process.argv[2] ?? 'https://REPLACE-WITH-YOUR-PAGES-URL'

// Keep the catalog's version honest against the package it describes.
const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'))
if (pkg.version !== PLUGIN.latestVersion) {
  console.warn(`warning: catalog entry says ${PLUGIN.latestVersion} but package.json says ${pkg.version}`)
}

const pageJson = `${JSON.stringify(buildPage(), null, 2)}\n`
const manifestJson = `${JSON.stringify(buildManifest('__SELF_ORIGIN__'), null, 2)}\n`

mkdirSync(out, { recursive: true })
writeFileSync(join(out, 'catalog-source.json'), `${JSON.stringify(buildManifest(origin), null, 2)}\n`)
writeFileSync(join(out, '_worker.js'), `/**
 * Generated by catalog/build-pages.mjs — do not edit by hand.
 * Advanced-mode Pages Worker: serves /v1/plugins (provider page) and
 * /catalog-source.json (manifest) with an explicit JSON content type. The
 * manifest endpoint is derived from the request origin so the source stays
 * self-consistent no matter which hostname it is deployed to.
 */
const PAGE = ${JSON.stringify(pageJson)}
const MANIFEST_TEMPLATE = ${JSON.stringify(manifestJson)}

const JSON_HEADERS = {
  'content-type': 'application/json; charset=utf-8',
  'cache-control': 'public, max-age=300',
  'access-control-allow-origin': '*',
}

export default {
  async fetch(request, env) {
    const url = new URL(request.url)
    if (url.pathname === '/v1/plugins') {
      return new Response(PAGE, { headers: JSON_HEADERS })
    }
    if (url.pathname === '/catalog-source.json') {
      const manifest = MANIFEST_TEMPLATE.replace('__SELF_ORIGIN__', url.origin)
      return new Response(manifest, { headers: JSON_HEADERS })
    }
    // Everything else: try the static assets (catalog-source.json among them).
    if (env.ASSETS !== undefined) {
      const asset = await env.ASSETS.fetch(request)
      if (asset.status === 404) return json({ error: 'not found' }, 404)
      return asset
    }
    return json({ error: 'not found' }, 404)
  },
}

function json(value, status = 200) {
  return new Response(JSON.stringify(value), { status, headers: JSON_HEADERS })
}
`)
console.log(`wrote pages/catalog-source.json (origin ${origin}) and pages/_worker.js`)