/**
 * Generated by catalog/build-pages.mjs — do not edit by hand.
 * Serves the v1 provider page at /v1/plugins with an explicit JSON content type.
 */
const PAGE = "{\n  \"schemaVersion\": \"1.0.0\",\n  \"generatedAt\": \"2026-09-17T09:08:13Z\",\n  \"revision\": \"2026-09-17T09:08:13Z\",\n  \"items\": [\n    {\n      \"id\": \"fal-imagegen\",\n      \"name\": \"dsh-fal-imagegen\",\n      \"displayName\": \"fal 生图（fal.ai 原生）\",\n      \"summary\": \"fal.ai 原生生图：FAL_KEY 设置卡片 + Agent 工具 fal_generate_image / fal_edit_image / fal_list_image_models，直连 queue.fal.run（Key 鉴权、队列轮询），默认模型 openai/gpt-image-2.5/flare。\",\n      \"homepage\": \"https://github.com/Enchanted0911/dsh-fal-imagegen\",\n      \"latestVersion\": \"0.1.0\",\n      \"license\": \"MIT\",\n      \"categories\": [\n        \"image-generation\",\n        \"agent-tools\",\n        \"interface\"\n      ],\n      \"keywords\": [\n        \"fal\",\n        \"fal.ai\",\n        \"text-to-image\",\n        \"image-to-image\",\n        \"gpt-image-2.5\",\n        \"nano-banana\",\n        \"flux\"\n      ],\n      \"repository\": {\n        \"url\": \"https://github.com/Enchanted0911/dsh-fal-imagegen\"\n      },\n      \"package\": {\n        \"registry\": \"npm\",\n        \"name\": \"dsh-fal-imagegen\"\n      },\n      \"publisher\": {\n        \"name\": \"wujunsheng\",\n        \"url\": \"https://github.com/Enchanted0911\"\n      },\n      \"capabilities\": {\n        \"required\": [\n          \"tools\",\n          \"settings\"\n        ],\n        \"optional\": [\n          \"attachments\",\n          \"systemPrompt\"\n        ]\n      },\n      \"compatibility\": {\n        \"apiVersion\": \"1.x\",\n        \"hosts\": [\n          \"dsh>=0.1.5-rc.2\"\n        ]\n      },\n      \"updatedAt\": \"2026-09-17T09:08:13Z\"\n    }\n  ],\n  \"page\": {\n    \"total\": 1\n  }\n}\n"

export function onRequestGet() {
  return new Response(PAGE, {
    headers: {
      'content-type': 'application/json; charset=utf-8',
      'cache-control': 'public, max-age=300',
      'access-control-allow-origin': '*',
    },
  })
}
